import 'package:hashtagg/shared/domain/entities/listing.dart';

var test_listings = [
  Listing(
    id: 1,
    title: 'iPhone 14 Pro 256GB',
    location: 'Москва',
    views: 145,
    description:
        'iPhone 14 Pro в отличном состоянии, без царапин. Полный комплект, чек в наличии.',
    publishedAt: '2024-01-15',
    price: 89000,
    status: ListingStatus.active,
    userId: 1,
    latitude: 55.7558,
    longitude: 37.6173,
  ),
  Listing(
    id: 2,
    title: 'MacBook Air M2 2023',
    location: 'Санкт-Петербург',
    views: 234,
    description:
        'Ноутбук в идеальном состоянии, использовался 3 месяца. Гарантия действует.',
    publishedAt: '2024-01-20',
    price: 115000,
    status: ListingStatus.active,
    userId: 2,
    latitude: 59.9343,
    longitude: 30.3351,
  ),
  Listing(
    id: 3,
    title: 'Диван угловой серый',
    location: 'Казань',
    views: 67,
    description:
        'Угловой диван в отличном состоянии, механизм трансформации работает исправно.',
    publishedAt: '2024-01-18',
    price: 25000,
    status: ListingStatus.active,
    userId: 3,
    latitude: 55.7887,
    longitude: 49.1221,
  ),
  Listing(
    id: 4,
    title: 'Велосипед горный Stels',
    location: 'Новосибирск',
    views: 89,
    description:
        'Горный велосипед 21 скорость, алюминиевая рама. Состояние хорошее.',
    publishedAt: '2024-01-10',
    price: 15000,
    status: ListingStatus.completed,
    userId: 4,
    latitude: 54.9884,
    longitude: 82.9357,
  ),
  Listing(
    id: 5,
    title: 'Кроссовки Nike Air Max',
    location: 'Екатеринбург',
    views: 178,
    description: 'Оригинальные кроссовки Nike, размер 42, новые в коробке.',
    publishedAt: '2024-01-22',
    price: 8500,
    status: ListingStatus.active,
    userId: 5,
    latitude: 56.8389,
    longitude: 60.6057,
  ),
  Listing(
    id: 6,
    title: 'Playstation 5 + 3 игры',
    location: 'Москва',
    views: 312,
    description:
        'PS5 в отличном состоянии + 3 диска с играми. Все документы, гарантия.',
    publishedAt: '2024-01-12',
    price: 45000,
    status: ListingStatus.active,
    userId: 1,
    latitude: 55.7522,
    longitude: 37.6215,
  ),
  Listing(
    id: 7,
    title: 'Холодильник Samsung No Frost',
    location: 'Самара',
    views: 45,
    description: 'Двухкамерный холодильник, система No Frost, почти новый.',
    publishedAt: '2024-01-25',
    price: 35000,
    status: ListingStatus.moderation,
    userId: 6,
    latitude: 53.2001,
    longitude: 50.1500,
  ),
  Listing(
    id: 8,
    title: 'Электросамокат Xiaomi',
    location: 'Краснодар',
    views: 201,
    description:
        'Электросамокат в хорошем состоянии, пробег 500 км, батарея держит отлично.',
    publishedAt: '2024-01-19',
    price: 22000,
    status: ListingStatus.active,
    userId: 7,
    latitude: 45.0355,
    longitude: 38.9753,
  ),
  Listing(
    id: 9,
    title: 'Гитара акустическая Yamaha',
    location: 'Ростов-на-Дону',
    views: 56,
    description: 'Акустическая гитара для начинающих и опытных музыкантов.',
    publishedAt: '2024-01-08',
    price: 12000,
    status: ListingStatus.completed,
    userId: 8,
    latitude: 47.2357,
    longitude: 39.7015,
  ),
  Listing(
    id: 10,
    title: 'Платье вечернее черное',
    location: 'Москва',
    views: 134,
    description: 'Элегантное вечернее платье, размер S, надевалось один раз.',
    publishedAt: '2024-01-23',
    price: 5500,
    status: ListingStatus.active,
    userId: 2,
    latitude: 55.7605,
    longitude: 37.6190,
  ),
  Listing(
    id: 11,
    title: 'Ноутбук Lenovo IdeaPad',
    location: 'Воронеж',
    views: 98,
    description: 'Ноутбук для работы и учебы, Core i5, 8GB RAM, SSD 256GB.',
    publishedAt: '2024-01-11',
    price: 32000,
    status: ListingStatus.active,
    userId: 9,
    latitude: 51.6720,
    longitude: 39.1843,
  ),
  Listing(
    id: 12,
    title: 'Стиральная машина Bosch',
    location: 'Нижний Новгород',
    views: 72,
    description:
        'Стиральная машина автомат, загрузка 6 кг, в рабочем состоянии.',
    publishedAt: '2024-01-05',
    price: 18000,
    status: ListingStatus.archived,
    userId: 4,
    latitude: 56.3269,
    longitude: 44.0059,
  ),
  Listing(
    id: 13,
    title: 'Детская коляска 3 в 1',
    location: 'Пермь',
    views: 167,
    description:
        'Коляска в отличном состоянии, люлька + прогулочный блок + автокресло.',
    publishedAt: '2024-01-21',
    price: 15000,
    status: ListingStatus.active,
    userId: 10,
    latitude: 58.0105,
    longitude: 56.2502,
  ),
  Listing(
    id: 14,
    title: 'Телевизор Samsung 55"',
    location: 'Уфа',
    views: 223,
    description: 'Smart TV 4K HDR, диагональ 55 дюймов, состояние идеальное.',
    publishedAt: '2024-01-17',
    price: 42000,
    status: ListingStatus.active,
    userId: 3,
    latitude: 54.7348,
    longitude: 55.9578,
  ),
  Listing(
    id: 15,
    title: 'Кресло офисное эргономичное',
    location: 'Челябинск',
    views: 91,
    description: 'Офисное кресло с регулировкой высоты и подлокотников.',
    publishedAt: '2024-01-14',
    price: 7500,
    status: ListingStatus.moderation,
    userId: 6,
    latitude: 55.1644,
    longitude: 61.4368,
  ),
  Listing(
    id: 16,
    title: 'Часы Apple Watch Series 8',
    location: 'Москва',
    views: 189,
    description:
        'Apple Watch 8 GPS, 45mm, алюминиевый корпус, все функции работают.',
    publishedAt: '2024-01-13',
    price: 32000,
    status: ListingStatus.active,
    userId: 1,
    latitude: 55.7480,
    longitude: 37.5970,
  ),
  Listing(
    id: 17,
    title: 'Кофемашина Delonghi',
    location: 'Санкт-Петербург',
    views: 78,
    description: 'Автоматическая кофемашина, готовит капучино и эспрессо.',
    publishedAt: '2024-01-09',
    price: 28000,
    status: ListingStatus.completed,
    userId: 5,
    latitude: 59.9386,
    longitude: 30.3141,
  ),
  Listing(
    id: 18,
    title: 'Сноуборд Burton + крепления',
    location: 'Сочи',
    views: 145,
    description: 'Сноуборд 158 см + крепления Burton, отличное состояние.',
    publishedAt: '2024-01-16',
    price: 18500,
    status: ListingStatus.active,
    userId: 8,
    latitude: 43.5992,
    longitude: 39.7257,
  ),
  Listing(
    id: 19,
    title: 'Фотоаппарат Canon EOS 2000D',
    location: 'Омск',
    views: 112,
    description:
        'Зеркальная камера для начинающих, объектив 18-55mm в комплекте.',
    publishedAt: '2024-01-07',
    price: 25000,
    status: ListingStatus.active,
    userId: 7,
    latitude: 54.9924,
    longitude: 73.3686,
  ),
  Listing(
    id: 20,
    title: 'Письменный стол белый',
    location: 'Тюмень',
    views: 63,
    description: 'Стол для работы и учебы, с выдвижными ящиками.',
    publishedAt: '2024-01-24',
    price: 6500,
    status: ListingStatus.active,
    userId: 9,
    latitude: 57.1522,
    longitude: 65.5272,
  ),
  Listing(
    id: 21,
    title: 'Беговая дорожка электрическая',
    location: 'Краснодар',
    views: 87,
    description: 'Беговая дорожка для дома, складная, скорость до 12 км/ч.',
    publishedAt: '2024-01-06',
    price: 22000,
    status: ListingStatus.archived,
    userId: 3,
    latitude: 45.0409,
    longitude: 38.9762,
  ),
  Listing(
    id: 22,
    title: 'Планшет Samsung Galaxy Tab',
    location: 'Москва',
    views: 156,
    description: 'Планшет 10 дюймов, 128GB, с чехлом и защитным стеклом.',
    publishedAt: '2024-01-20',
    price: 18000,
    status: ListingStatus.active,
    userId: 2,
    latitude: 55.7630,
    longitude: 37.6320,
  ),
  Listing(
    id: 23,
    title: 'Микроволновая печь LG',
    location: 'Волгоград',
    views: 44,
    description: 'Микроволновка с грилем, мощность 800W, объем 20л.',
    publishedAt: '2024-01-26',
    price: 4500,
    status: ListingStatus.moderation,
    userId: 10,
    latitude: 48.7080,
    longitude: 44.5133,
  ),
];
